name: Push to Both Repositories

on:
  push:
    branches:
      - main

jobs:
  push-to-both:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'jperradin'
          git config --global user.email 'julien.perradin@protonmail.com'

      - name: Add backup remote
        run: git remote add backup https://github.com/jperradin/backup-nexus.git

      - name: Push to both repositories
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://jperradin:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/TheDisorderedOrganization/nexus.git
          git remote set-url backup https://jperradin:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jperradin/backup-nexus.git
          git push origin main
          git push backup main